name: petetco
description: "This app for manage the pet"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  hooks_riverpod: ^2.5.2
  riverpod_annotation: ^2.3.5
  smooth_page_indicator: ^1.2.0+3
  gap: ^3.0.1
  get:
  flutter_vector_icons: ^2.0.0
  lottie: ^3.1.3
  http: ^1.2.2
  awesome_dialog: ^3.2.1


 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.19
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/logo.png  # Optional: path to the splash screen logo
  android: true
  ios: true
  fullscreen: true     # Optional: make the splash screen fullscreen


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
